name: CLA-Check
on: push

jobs:
  check-cla-sign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check CLA signature
      run: |
        CLAFILE="./LICENSES/CLA-signed-list.md"
        
        if grep -q ${{ github.actor }} "$CLAFILE"; then
          echo "CLA signed OK!"
        else
          echo "CLA is not signed for ${{ github.actor }}, please agree with CLA and add your username to $CLAFILE"
          exit 1;
        fi